abstract type AbstractControlToolboxFunction{time_dependence} <: Function end

@time_dependence_function Hamiltonian, AbstractControlToolboxFunction
@time_dependence_function HamiltonianVectorField, AbstractControlToolboxFunction
@time_dependence_function VectorField, AbstractControlToolboxFunction
@time_dependence_function LagrangeFunction, AbstractControlToolboxFunction
@time_dependence_function DynamicsFunction, AbstractControlToolboxFunction
@time_dependence_function StateConstraintFunction, AbstractControlToolboxFunction
@time_dependence_function ControlConstraintFunction, AbstractControlToolboxFunction
@time_dependence_function MixedConstraintFunction, AbstractControlToolboxFunction
@time_dependence_function ControlFunction, AbstractControlToolboxFunction
@time_dependence_function MultiplierFunction, AbstractControlToolboxFunction