abstract type AbstractControlFunction{T, time_dependence} end

@time_dependence_function Hamiltonian, AbstractControlFunction
@time_dependence_function HamiltonianVectorField, AbstractControlFunction
@time_dependence_function VectorField, AbstractControlFunction
@time_dependence_function LagrangeControlFunction, AbstractControlFunction
@time_dependence_function DynamicsControlFunction, AbstractControlFunction